### Задание 1

In [2]:
import numpy as np

In [81]:
def create_nparray ():
    n = int(input('Input number: '))
    if n >= 0:
        np_array = np.arange(0,n)
        return np_array[::-1]
    elif n < 0:
        np_array = np.arange(n+1,1)
        return np_array

In [82]:
create_nparray()

Input number: -10


array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

### Задание 2

In [83]:
def create_matrix ():
    my_matrix = np.diag(create_nparray())
    print('My sum:', sum(np.diag(my_matrix)))
    return my_matrix

In [84]:
create_matrix()

Input number: -10
My sum: -45


array([[-9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

### Задание 3

In [3]:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
np.linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [39]:
def max_cosin(matrix, new_user_data):
    new_user_data_length = np.linalg.norm(new_user_data)
    result = []
    for matrix_el in matrix:
        matrx_el_lehgth = np.linalg.norm(matrix_el)
        result.append(np.dot(new_user_data, matrix_el)/(matrx_el_lehgth*new_user_data_length))
    print(result)
    return users_stats[result.index(max(result))]

In [40]:
max_cosin(users_stats,next_user_stats)

[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]


array([0, 1, 1, 0, 0, 0])